### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by paols1977** [chiragsrvstv/labAuth#3]
Need help to make this work with my firebase account. Do you help? Thanks

**Comment by chiragsrvstv** [comment]
For a detailed use case you can take a look at this https://github.com/chiragsrvstv/labAuth/blob/master/PCTUseCases%20forCollegesv2.pdf to get an exact view of the problem(UseCase 2) this project intends to solve.

So this application is used to scan ID cards of volunteers when they're just about to enter a particular lab. It then gives out the information like when and how many times they accessed this particular lab or other labs(if any). Then the person using our application(lab technicians) to scan ID cards can then add this as a fresh entry for the volunteer whose card has just been scanned along with some of the mentioned details in the above useCase. 

So to mimic the ID cards you can create a dummy QR code holding volunteer ID and can then scan it to view the details, remember that the ID should be present in our firebase database under volunteers field like this: (Here 1001 is an ID of the volunteer that will be printed on its ID card probably in the form of QR/Bar code.)
![image](https://user-images.githubusercontent.com/32494927/91797301-d80c4900-ec3f-11ea-98bc-a9ce72ed541b.png)

Now if you'll scan the code, all the data about this particular volunteer will be shown and you can finally add/update the entry for them referring that this person has accessed the lab now. The new entry along with the timestamp will then be reflected in your database.
